---
params:
  anonymous: false

title: |
  AI Chatbots in K-12 Education: An Experimental Study of Socratic vs. Non-Socratic AI Agents and the Role of Step-by-Step Reasoning

author:
  - "`r ifelse(!params$anonymous, 'Andrea Blasco', 'Anonymous') `":
      institute:
        - jrc
      correspondence: "yes"
      email: "`r ifelse(!params$anonymous, 'andrea.blasco@ec.europa.eu', 'Email') `"
  - "`r ifelse(!params$anonymous, 'Vicky Charisi', 'Anonymous') `":
      institute: [jrc, harvard]
      correspondence: "yes"
      email: "`r ifelse(!params$anonymous, 'vcharisi@cyber.harvard.edu', 'Email') `"

institute:
  - jrc: "`r ifelse(!params$anonymous, 'European Commission, Joint Research Centre, Brussels, Belgium', 'Anonymous Institute') `"
  - harvard: "`r ifelse(!params$anonymous, 'Harvard University, Berkman Klein Center, Cambridge, MA, USA', 'Anonymous Institute')`"

date: |
  `r format(Sys.Date(), 'This version: %B %d, %Y')`

fontsize: 11pt # 11
linestretch: 1.25 # 1.25
colorlinks: true
link-citations: true
graphics: true
tables: true
mainfont: Helvetica
geometry: margin=2cm
always_allow_html: true

bibliography: [refs.bib]
csl: [hssc.csl]

header-includes: |
  ```{=latex}
  \usepackage[utf8]{inputenc}
  
  % Break sections into new page
  \usepackage{titlesec}
  \newcommand{\sectionbreak}{\clearpage}
  \usepackage{soul} % \hl{} = highlights

  % Table caption 
  \usepackage{caption} 
  \captionsetup[table]{skip=8pt}

  % Table packages
  \usepackage{longtable}
  \usepackage{array}
  \usepackage{multirow}
  \usepackage{wrapfig}
  \usepackage{float}
  \usepackage{colortbl}
  \usepackage{pdflscape}
  \usepackage{tabu}
  \usepackage{threeparttable}
  \usepackage{threeparttablex}
  \usepackage[normalem]{ulem}
  \usepackage{makecell}
  \usepackage{xcolor}

  % Move all figures at the end
  \usepackage[nolists, nomarkers]{endfloat}
  \DeclareDelayedFloatFlavour*{longtable}{table}

  %\graphicspath{}
  ```
---

<!-- # The Impact of Large Language Models on Students: A Randomised Study of Socratic vs. Non-Socratic AI and the Role of Step-by-Step Reasoning -->


```{r setup, include = FALSE}
library(patchwork)
library(figpatch)

knitr::opts_chunk$set(
    echo = FALSE,
    cache = FALSE,
    dev = ifelse(knitr::is_html_output(), "png", "pdf"),
    dpi = 100
)
```

```{r, child = "00-abstract.Rmd"}
```

```{r, child = "01-intro.Rmd"}
```

```{r, child = "02-literature.Rmd"}
```

```{r, child = "02-methods.Rmd"}
```

```{r, child = "03-results.Rmd"}
```

```{r, child = "04-discussion.Rmd"}
```

# References {-}

::: {#refs}
:::

```{r child = "90-supporting.Rmd"}
```

```{r child = "91-statements.Rmd"}
```

```{r child = "99-questionnaire.Rmd"}
```

